[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Netlify handles Next.js apps automatically
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCjPifC8njhnEGiUrYKo5HiuiQd4dTny0k"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "valoriyaservice.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "valoriyaservice"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "valoriyaservice.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "973884239952"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:973884239952:web:valoriyaservice"
